### ISSUE TITLE
Stuck on "initializing" when loading

### ISSUE THREAD

**Issue by pushontom** [leftstick/teams-ubuntu#1]
When loading up the app, it gets stuck on initialising. Reload (CTRL+R) doesn't bring it back. Seems like something is cached somewhere.

**Comment by pushontom** [comment]
This resolved the issue: 
`rm -rf ~/.config/teams-ubuntu`

**Comment by leftstick** [comment]
@pushontom so, your issue was solved by the action you mentioned?

**Comment by pushontom** [comment]
Just tested and it's only temporarily resolves it. I have to remove that folder each time I start the application.

**Comment by leftstick** [comment]
I tried give a fix in `1.1.2`, would you like to test if my fix work?

**Comment by pushontom** [comment]
Downloading now, will report back. Thanks @leftstick

**Comment by pushontom** [comment]
It works, however I have to be VERY quick at entering my login details otherwise it keeps refreshing itself. 

It also doesn't save my credentials anymore. 

I'm going to delete that folder and try again

**Comment by pushontom** [comment]
Will mark as new issue

**Comment by leftstick** [comment]
My mistake, i forgot to differentiate between login page and app page. 

I tried to watch `initializing` state, if the whole app stays on that state for over `5s`, will treat it as failed to launch, below actions will be done step by step:

1. clean all storageData and sessionData
2. reload app

That's why you found login page refreshed in few seconds, and you need to "login" each time you start app

**Comment by pushontom** [comment]
Please can you explain: "clean all storageData and sessionData" so we know exactly what to clean?

**Comment by leftstick** [comment]
"clean all storageData and sessionData" was what i've done in `1.1.2` for your original issue "Stuck on initializing".

I called electron API [preload.js](https://github.com/leftstick/teams-ubuntu/blob/1.1.2/inject/preload.js#L13-L24).

But it cause another two issues as you reported "credentials are no longer saved", "keep refreshes in every 5s while in login page".

So i moved to next fix which is `1.1.3`

**Comment by pushontom** [comment]
Ah apologies, didn't see 1.1.3. My bad. 

Thanks for the updates, much appreciated
