### ISSUE TITLE
Does it work with 32-bit?

### ISSUE THREAD

**Issue by csg10** [leftstick/teams-ubuntu#11]
Hello, 
really sorry if this is a very trivial question or if this is not the place to put this question, but I am a very beginner user.

Thank you for creating this. It is not clear to me if this can work on Ubuntu 16.04 32-bit. Also it is not clear to me how to install it, does it have to be done starting from downloading the folder on the description?

Thank you very much and sorry again if this is not the place.

**Comment by leftstick** [comment]
Try download `32bit` from https://github.com/leftstick/teams-ubuntu/releases/download/1.1.7/Microsoft-Teams-linux-ia32.zip
