### ISSUE TITLE
Credentials are no longer saved (1.1.2)

### ISSUE THREAD

**Issue by pushontom** [leftstick/teams-ubuntu#2]
I have to enter my details each time I start the app

**Comment by leftstick** [comment]
I tried to reload app with storageData and sessionData cleaned while i found app stays at `initializing` state over `5s`. Now, it seems credentials are saved in storageData. So i removed this part. 

Only clean sessionData while reload app(This is for [issue-1](https://github.com/leftstick/teams-ubuntu/issues/1))
