### ISSUE TITLE
Include 'how to get started' in README

### ISSUE THREAD

**Issue by ucg8j** [leftstick/teams-ubuntu#6]
This looks like really useful software. I've just had the experience of audio and video not being supported through Microsoft teams on Ubuntu. 

I've so far:
1. Downloaded the `Microsoft Teams-linux-x64.zip` file from the README. 
2. Unzipped it.
3. Installed electron
4. cd into `/Microsoft Teams-linux-x64`
5. npm install; npm start

Any help would be appreciated.

I'm on Ubuntu 16.

**Comment by leftstick** [comment]
`Microsoft Teams-linux-x64.zip` is all you need. You shouldn't install anything else if you are using `Microsoft Teams-linux-x64.zip`. Just doucle click to open the app.

And what's the error you have then?

**Comment by ucg8j** [comment]
@leftstick I've since changed computers and I'm no longer using Ubuntu 16. So I can't say what the error was now. Thanks for getting back to me. If you like, I can submit a PR to add to the README a '**Getting Started**' section to help users adopt this software.

**Comment by leftstick** [comment]
nice, thank you
