### ISSUE TITLE
Ubuntu "unsupported browser"

### ISSUE THREAD

**Issue by pushontom** [leftstick/teams-ubuntu#9]
Yesterday the app stopped loading and returns the error "unsupported browser". I'm not sure if this is an issue with Chrome, Teams, or the teams-ubuntu wrapper.

**Comment by mlukasik1** [comment]
+1. I'm unable to use it.

**Comment by leftstick** [comment]
Please try `1.1.6`

**Comment by pushontom** [comment]
Thanks again leftstick
